imports:
    - { resource: set/contao.yaml }

parameters:
    exclude_files:
        - '*/Resources/*'

    skip:
        PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer:
            - '*/DependencyInjection/Configuration.php'

        SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff.UnusedMethod:
            - 'core-bundle/src/Controller/InitializeController.php'

        SlevomatCodingStandard\Sniffs\Variables\UnusedVariableSniff:
            - 'core-bundle/tests/Session/Attribute/ArrayAttributeBagTest.php'

    cache_directory: '%sys_get_temp_dir%/ecs_default_cache'
