imports:
    - { resource: set/contao.yaml }

parameters:
    exclude_files:
        - '*/Resources/*'

    skip:
        Symplify\CodingStandard\Sniffs\Naming\AbstractClassNameSniff:
            - '*TestCase.php'

    cache_directory: '%sys_get_temp_dir%/ecs_default_cache'
